name: 🚀 Deploy website on push
on: 
  push:
      tags:
        - beta/**
        - release/**
  
jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
    - name: 🚚 Get latest code
      uses: actions/checkout@v4

    - name: Get Tag info
      run: echo "Running workflow for tag ${{ github.ref_name }}"
    
    - name: 📂 Sync files into release if release/ tag
      if: startsWith(github.ref_name, 'release/')
      uses: SamKirkland/FTP-Deploy-Action@v4.3.5
      with:
        server: winweb20.servicehoster.ch
        username: h208686_dta24_bs
        password: ${{ secrets.SEVIS_SECRET }}
        local-dir: ./public/
        server-dir: ./
        
    - name: Sync files into beta if beta/ tag
      if: startsWith(github.ref_name, 'beta/')
      uses: SamKirkland/FTP-Deploy-Action@v4.3.5
      with:
        server: winweb20.servicehoster.ch
        username: h208686_dta24_bs
        password: ${{ secrets.SEVIS_SECRET }}
        local-dir: ./public/
        server-dir: ./beta/
